export const MOROCCAN_CITIES = [
  "Agadir",
  "Al Hoceima",
  "Azrou",
  "Ben Guerir",
  "Beni Ensar",
  "Béni Mellal",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bouskoura",
  "Casablanca",
  "Dcheira El Jihadia",
  "El Jadida",
  "El Kelaa Des Sraghna",
  "El Ksar El Kebir",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Fnideq",
  "Fquih Ben Salah",
  "Guelmim",
  "Guercif",
  "Inezgane",
  "Kénitra",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Lahraouyine",
  "Larache",
  "Lkliaa",
  "M'diq",
  "Marrakech",
  "Martil",
  "Meknès",
  "Midelt",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouazzane",
  "Oued Zem",
  "Oujda",
  "Oulad Teima",
  "Rabat",
  "Safi",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirat",
  "Souk El Arbaa",
  "Suq as-Sabt Awlad an-Nama",
  "Tan-Tan",
  "Tanger",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Tétouan",
  "Tifelt",
  "Tiznit",
  "Youssoufia",
  "Autre"
];
