export interface Perfume {
  id: string;
  name: string;
  brand: string;
  category: "homme" | "femme" | "unisexe";
  type: string;
  family: string;
  image: string;
  badge?: string;
  description: string;
  topNotes: string;
  heartNotes: string;
  baseNotes: string;
  price5ml: number;
  price10ml: number;
  rating: number;
  inStock: boolean;
}

export const PRODUCTS: Perfume[] = [
  // --- HOMME ---
  {
    id: "sauvage-dior-edp",
    name: "Sauvage",
    brand: "Dior",
    category: "homme",
    type: "Eau de Parfum",
    family: "Boisé Épicé",
    image: "/assets/images/sauvage.jpg",
    badge: "Incontournable",
    description: "Une fraîcheur succulente et épicée enrichie d'un absolu de vanille enveloppant.",
    topNotes: "Bergamote de Calabre, Poivre de Sichuan",
    heartNotes: "Star Anis, Noix de Muscade, Lavande",
    baseNotes: "Absolu de Vanille de Papouasie, Ambroxan",
    price5ml: 130,
    price10ml: 230,
    rating: 4.9,
    inStock: true,
  },
  {
    id: "phantom-rabanne",
    name: "Phantom",
    brand: "Paco Rabanne",
    category: "homme",
    type: "Extrait de Parfum",
    family: "Aromatique Futuriste",
    image: "/assets/images/phantom.jpeg",
    badge: "Nouveauté",
    description: "La rencontre audacieuse d'une lavande rafraîchissante et d'une vanille addictive.",
    topNotes: "Citron tonique, Zeste de Citron",
    heartNotes: "Lavande futée, Pomme, Fumée",
    baseNotes: "Vanille crémeuse, Vétiver, Huile de Patchouli",
    price5ml: 110,
    price10ml: 190,
    rating: 4.7,
    inStock: true,
  },
  {
    id: "creed-aventus",
    name: "Aventus",
    brand: "Creed",
    category: "homme",
    type: "Eau de Parfum",
    family: "Fruité Boisé",
    image: "/assets/images/dior.jpg",
    badge: "Prestige Niche",
    description: "Un parfum mythique célébrant la force, le pouvoir et la réussite masculine.",
    topNotes: "Ananas royal, Bergamote, Cassis, Pomme",
    heartNotes: "Bouleau fumé, Patchouli, Jasmin floral",
    baseNotes: "Mousse de chêne, Musc, Ambre gris, Vanille",
    price5ml: 190,
    price10ml: 340,
    rating: 5.0,
    inStock: true,
  },
  {
    id: "jpg-le-male-elixir",
    name: "Le Male Elixir",
    brand: "Jean Paul Gaultier",
    category: "homme",
    type: "Parfum Intense",
    family: "Oriental Ambré",
    image: "/assets/images/Perfume_bottle_on_black_pedestal_202609010307.jpeg",
    badge: "Bestseller 2026",
    description: "Un sillage brûlant d'une sensualité extrême, où la fève tonka s'embrase au contact du miel.",
    topNotes: "Lavande intense, Menthe fraîche",
    heartNotes: "Fève Tonka, Miel doré",
    baseNotes: "Benzoin, Vanille noire",
    price5ml: 135,
    price10ml: 235,
    rating: 4.9,
    inStock: true,
  },

  // --- FEMME ---
  {
    id: "scandal-jpg",
    name: "Scandal",
    brand: "Jean Paul Gaultier",
    category: "femme",
    type: "Eau de Parfum",
    family: "Gourmand Floral",
    image: "/assets/images/scandal.jpg",
    badge: "Sensuel & Gourmand",
    description: "Un miel gourmand et élégant associé à l'envoûtant gardénia et au patchouli intense.",
    topNotes: "Orange Sanguine, Mandarine",
    heartNotes: "Miel, Gardénia, Fleur d'Oranger, Pêche",
    baseNotes: "Patchouli, Cire d'abeille, Caramel, Réglisse",
    price5ml: 125,
    price10ml: 215,
    rating: 4.8,
    inStock: true,
  },
  {
    id: "libre-intense-ysl",
    name: "Libre Intense",
    brand: "Yves Saint Laurent",
    category: "femme",
    type: "Eau de Parfum",
    family: "Floral Oriental",
    image: "/assets/images/collection.jpeg",
    badge: "Coup de Cœur",
    description: "Le parfum d'une femme libre à l'instinct sauvage qui rugit de liberté.",
    topNotes: "Essence de Bergamote, Huile de Mandarine",
    heartNotes: "Fleur d'Oranger du Maroc, Lavande, Orchidée",
    baseNotes: "Absolu de Vanille de Madagascar, Ambre gris",
    price5ml: 135,
    price10ml: 235,
    rating: 4.9,
    inStock: true,
  },
  {
    id: "baccarat-rouge-540",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    category: "femme",
    type: "Extrait de Parfum",
    family: "Ambré Boisé",
    image: "/assets/images/Brandinfo.jpeg",
    badge: "Niche Étoilée",
    description: "Une alchimie poétique où le jasmin et le safran s'accordent aux notes minérales de l'ambre gris.",
    topNotes: "Safran doré, Jasmin grandiflorum",
    heartNotes: "Bois d'ambre, Ambre gris",
    baseNotes: "Résine de sapin, Cèdre de Virginie",
    price5ml: 220,
    price10ml: 390,
    rating: 5.0,
    inStock: true,
  },
  {
    id: "coco-mademoiselle-chanel",
    name: "Coco Mademoiselle",
    brand: "Chanel",
    category: "femme",
    type: "Eau de Parfum Intense",
    family: "Chypré Oriental",
    image: "/assets/images/Create_luxury_perfume_advertisin…_2K_202609010303.jpeg",
    badge: "Élégance Absolue",
    description: "L'essence d'une femme libre et audacieuse. Un oriental au caractère affirmé et d'une étonnante fraîcheur.",
    topNotes: "Orange de Sicile, Bergamote de Calabre",
    heartNotes: "Extrait de Rose, Jasmin de Grasse",
    baseNotes: "Patchouli d'Indonésie, Vétiver, Vanille",
    price5ml: 145,
    price10ml: 255,
    rating: 4.9,
    inStock: true,
  },

  // --- UNISEXE ---
  {
    id: "tobacco-vanille-tom-ford",
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    category: "unisexe",
    type: "Eau de Parfum",
    family: "Oriental Épicé",
    image: "/assets/images/Perfume_bottle_on_black_pedestal_202609010307.jpeg",
    badge: "Iconique",
    description: "Un parfum opulent, chaleureux et classique rappelant l'atmosphère d'un club de gentlemen anglais.",
    topNotes: "Feuilles de Tabac, Épices douces",
    heartNotes: "Fève Tonka, Fleur de Tabac, Vanille, Cacao",
    baseNotes: "Accord de Fruits Secs, Notes Boisées",
    price5ml: 180,
    price10ml: 320,
    rating: 4.9,
    inStock: true,
  },
  {
    id: "santal-33-le-labo",
    name: "Santal 33",
    brand: "Le Labo",
    category: "unisexe",
    type: "Eau de Parfum",
    family: "Boisé Cuiré",
    image: "/assets/images/collection.jpeg",
    badge: "Culte",
    description: "L'esprit du grand ouest américain immortalisé dans un sillage de santal et de cuir fumé.",
    topNotes: "Cardamome, Iris, Violette",
    heartNotes: "Bois de Santal, Papyrus",
    baseNotes: "Cèdre, Cuir, Ambre doux",
    price5ml: 185,
    price10ml: 330,
    rating: 4.8,
    inStock: true,
  }
];
